# Generated by Django 5.2.10 on 2026-01-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('eliminated', models.BooleanField(default=False)),
            ],
        ),
    ]
