# Generated by Django 4.2.27 on 2026-01-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureSorter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimagemodel',
            name='file_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
